package repartido0acuña;

public class AnexoEjercicio10 {
  
  
  /*
   * El String corresponde a una copia del código de la página de la FING-UdelaR, consultada el día 6/3/2024.
   * URL: https://www.fing.edu.uy/es/telefonos
   * */
  String p = "\n"
      + "\n"
      + "<!DOCTYPE html>\n"
      + "<html lang=\"es\" dir=\"ltr\">\n"
      + "  <head>\n"
      + "    <meta charset=\"utf-8\" />\n"
      + "<script>var _paq = _paq || [];(function(){var u=((\"https:\" == document.location.protocol) ? \"https://www.fing.edu.uy/matomo/\" : \"https://www.fing.edu.uy/matomo/\");_paq.push([\"setSiteId\", \"1\"]);_paq.push([\"setTrackerUrl\", u+\"matomo.php\"]);_paq.push([\"setDoNotTrack\", 1]);_paq.push([\"setCookieDomain\", \".www.fing.edu.uy\"]);if (!window.matomo_search_results_active) {_paq.push([\"trackPageView\"]);}_paq.push([\"setIgnoreClasses\", [\"no-tracking\",\"colorbox\"]]);_paq.push([\"enableLinkTracking\"]);var d=document,g=d.createElement(\"script\"),s=d.getElementsByTagName(\"script\")[0];g.type=\"text/javascript\";g.defer=true;g.async=true;g.src=u+\"matomo.js\";s.parentNode.insertBefore(g,s);})();</script>\n"
      + "<meta name=\"Generator\" content=\"Drupal 10 (https://www.drupal.org)\" />\n"
      + "<meta name=\"MobileOptimized\" content=\"width\" />\n"
      + "<meta name=\"HandheldFriendly\" content=\"true\" />\n"
      + "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n"
      + "<link rel=\"icon\" href=\"/sites/default/files/favicon.ico\" type=\"image/vnd.microsoft.icon\" />\n"
      + "<link rel=\"alternate\" hreflang=\"es\" href=\"https://www.fing.edu.uy/es/telefonos\" />\n"
      + "<link rel=\"canonical\" href=\"https://www.fing.edu.uy/es/telefonos\" />\n"
      + "<link rel=\"shortlink\" href=\"https://www.fing.edu.uy/es/node/3186\" />\n"
      + "<link rel=\"prev\" href=\"/es/node/47611\" />\n"
      + "<link rel=\"up\" href=\"/es/comunicacion\" />\n"
      + "<link rel=\"next\" href=\"/es/go/contacto\" />\n"
      + "\n"
      + "    <title>Teléfonos | Facultad de Ingeniería</title>\n"
      + "    <link rel=\"stylesheet\" media=\"all\" href=\"/sites/default/files/css/css_4U7C-w485m3QzVytsNSg-J7UGuNk4h8mdkQqCKA1Gt0.css?delta=0&amp;language=es&amp;theme=fing2&amp;include=eJw9zNEKgCAMheEXEge9UKw5S9IN5oh8-4Kkq_PdnJ-wsiQ0oInoBzcODV2bwjehj-7cYMPOwTCVG7qPyiEX2ZdpOjkVV1uRSC0VFfgVs6n4259vwWtDewCm1i_p\" />\n"
      + "<link rel=\"stylesheet\" media=\"all\" href=\"/sites/default/files/css/css_YH1Br5AlHtnYkGoCmowwMOYRNW36PGJa0Fj55h4bx0o.css?delta=1&amp;language=es&amp;theme=fing2&amp;include=eJw9zNEKgCAMheEXEge9UKw5S9IN5oh8-4Kkq_PdnJ-wsiQ0oInoBzcODV2bwjehj-7cYMPOwTCVG7qPyiEX2ZdpOjkVV1uRSC0VFfgVs6n4259vwWtDewCm1i_p\" />\n"
      + "\n"
      + "    \n"
      + "  </head>\n"
      + "  <body class=\"page-node-3186 page-node-type-book node-3186 node-type--book path-node language--es\">\n"
      + "        <a href=\"#main-content\" class=\"visually-hidden focusable\">\n"
      + "      Pasar al contenido principal\n"
      + "    </a>\n"
      + "    \n"
      + "      <div class=\"dialog-off-canvas-main-canvas\" data-off-canvas-main-canvas>\n"
      + "    <div class=\"page\">\n"
      + "\n"
      + "               <div class=\"container\">\n"
      + "          <div class=\"row\">\n"
      + "            <div class=\"col-sm-6\">\n"
      + "              \n"
      + "  <div class=\"udelar block--logofing block--type-basic block block--basic block--fing2-logofing\">\n"
      + "\n"
      + "  \n"
      + "    \n"
      + "\n"
      + "            \n"
      + "            <div class=\"field field--name-body field--type-text-with-summary field--label-hidden field__item\"><p><a href=\"/\"><img alt=\"fing\" data-entity-type=\"file\" data-entity-uuid=\"31c620aa-3a3f-457f-901f-8140a1c5f3d4\" height=\"70px\" src=\"/sites/default/files/inline-images/logofingnew_0.png\" width=\"543\" loading=\"lazy\"></a></p></div>\n"
      + "      \n"
      + "      \n"
      + "  </div>\n"
      + "\n"
      + "\n"
      + "          </div> \n"
      + "          <div class=\"col-sm-6\">\n"
      + "            <div class = \"arriba\">\n"
      + "                \n"
      + "  <div class=\"search-block-form needs-validation block--searchform block block--fing2-searchform\" data-drupal-selector=\"search-block-form\" role=\"search\">\n"
      + "\n"
      + "  \n"
      + "    \n"
      + "\n"
      + "            \n"
      + "<form action=\"/es/search/node\" method=\"get\" id=\"search-block-form\" accept-charset=\"UTF-8\" class=\"form form-inline\">\n"
      + "  <div class=\"js-form-item form-item js-form-type-search form-item-keys js-form-item-keys form-no-label form-group\">\n"
      + "      \n"
      + "  \n"
      + "  \n"
      + "  \n"
      + "  \n"
      + "  \n"
      + "<input title=\"Escriba lo que quiere buscar.\" data-drupal-selector=\"edit-keys\" type=\"search\" id=\"edit-keys\" name=\"keys\" value=\"\" size=\"20\" maxlength=\"128\" placeholder=\"Buscar\" class=\"form-search form-control\">\n"
      + "\n"
      + "\n"
      + "  \n"
      + "  \n"
      + "  \n"
      + "  \n"
      + "  </div>\n"
      + "<div data-drupal-selector=\"edit-actions\" class=\"form-actions js-form-wrapper form-wrapper\" id=\"edit-actions--2\">\n"
      + "\n"
      + "<input class=\"btn btn-primary js-form-submit form-submit btn btn-primary\" data-drupal-selector=\"edit-submit\" type=\"submit\" id=\"edit-submit\" value=\"Buscar\">\n"
      + "</div>\n"
      + "\n"
      + "</form>\n"
      + "\n"
      + "      \n"
      + "  </div>\n"
      + "\n"
      + "\n"
      + "            </div>\n"
      + "             <div class = \"abajo\">\n"
      + "                \n"
      + "  <div class=\"usuario block--useraccountmenu block block--fing2-useraccountmenu block--system-menu\">\n"
      + "\n"
      + "  \n"
      + "    \n"
      + "\n"
      + "            \n"
      + "  \n"
      + "\n"
      + "\n"
      + "  <ul class=\"nav navbar-nav\">\n"
      + "                          \n"
      + "                \n"
      + "        <li class=\"nav-item\">\n"
      + "                      <a href=\"/es/user/login\" class=\"nav-link\" data-drupal-link-system-path=\"user/login\">Iniciar sesión</a>\n"
      + "                  </li>\n"
      + "            </ul>\n"
      + "\n"
      + "\n"
      + "      \n"
      + "  </div>\n"
      + "\n"
      + "\n"
      + "            </div>\n"
      + "            \n"
      + "          </div> \n"
      + "        </div>\n"
      + "        </div>\n"
      + "          \n"
      + "\n"
      + "  \n"
      + "\n"
      + "\n"
      + "<nav class=\"navbar navbar-expand-lg justify-content-between navbar-light sticky-top bg-light\">\n"
      + "      <div class=\"container\">\n"
      + "  \n"
      + "            \n"
      + "  <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\".navbar-collapse\" aria-controls=\"navbar-collapse\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n"
      + "    <span class=\"navbar-toggler-icon\"></span>\n"
      + "  </button>\n"
      + "\n"
      + "  <div class=\"collapse navbar-collapse\">\n"
      + "                  <div class=\"mr-auto\">\n"
      + "            \n"
      + "  <div class=\"block--primarylinks block block--fing2-primarylinks block--system-menu\">\n"
      + "\n"
      + "  \n"
      + "    \n"
      + "\n"
      + "            \n"
      + "  \n"
      + "\n"
      + "\n"
      + "  <ul class=\"nav\">\n"
      + "                          \n"
      + "                \n"
      + "        <li class=\"nav-item dropdown\">\n"
      + "                      <a href=\"/index.php/institucional\" class=\"nav-link dropdown-toggle\" data-bs-toggle=\"dropdown\">Institucional</a>\n"
      + "                          <div class=\"dropdown-menu\">\n"
      + "              <a href=\"/index.php/es/institucional/presentaci%C3%B3n\" title=\"Presentación\" class=\"dropdown-item\" data-drupal-link-system-path=\"node/6724\">Presentación</a>\n"
      + "              <a href=\"/index.php/es/institucional/autoridades\" title=\"Autoridades\" class=\"dropdown-item\" data-drupal-link-system-path=\"node/2865\">Autoridades</a>\n"
      + "              <a href=\"/index.php/es/node/47611\" class=\"dropdown-item\" data-drupal-link-system-path=\"node/47611\">Identidad Visual</a>\n"
      + "              <a href=\"/index.php/es/institucional/dptos-administrativos-y-servicios\" title=\"Dptos. Administrativos y Servicios\" class=\"dropdown-item\" data-drupal-link-system-path=\"node/226\">Gestión administrativa</a>\n"
      + "              <a href=\"/index.php/es/institucional/comisiones-de-cogobierno\" title=\"Comisiones de la Facultad\" class=\"dropdown-item\" data-drupal-link-system-path=\"node/196\">Comisiones de cogobierno</a>\n"
      + "              <a href=\"/index.php/es/gestion\" title=\"Normativa y formularios\" class=\"dropdown-item\" data-drupal-link-system-path=\"node/3085\">Normativa y formularios</a>\n"
      + "              <a href=\"/index.php/es/node/48447\" class=\"dropdown-item\" data-drupal-link-system-path=\"node/48447\">Datos, evaluaciones y perspectivas</a>\n"
      + "              <a href=\"/index.php/es/institucional/s%C3%ADntesis-hist%C3%B3rica\" title=\"Síntesis Histórica\" class=\"dropdown-item\" data-drupal-link-system-path=\"node/2873\">Síntesis histórica</a>\n"
      + "              <a href=\"/index.php/es/institucional/relaciones-internacionales\" class=\"dropdown-item\" data-drupal-link-system-path=\"node/24178\">Relaciones internacionales</a>\n"
      + "              <a href=\"/index.php/es/informacioncovidfing\" class=\"dropdown-item\" data-drupal-link-system-path=\"node/37580\">Historial de medidas COVID-19</a>\n"
      + "              <a href=\"/index.php/es/institucional/organizaciones\" class=\"dropdown-item\" data-drupal-link-system-path=\"node/3167\">Organizaciones</a>\n"
      + "  </div>\n"
      + "                              </li>\n"
      + "                      \n"
      + "                \n"
      + "        <li class=\"nav-item dropdown\">\n"
      + "                      <a href=\"/index.php/es/institutos\" title=\"Institutos\" class=\"nav-link dropdown-toggle\" data-bs-toggle=\"dropdown\" data-drupal-link-system-path=\"node/3039\">Institutos</a>\n"
      + "                          <div class=\"dropdown-menu\">\n"
      + "              <a href=\"/index.php/es/ia\" title=\"Agrimensura\" class=\"dropdown-item\" data-drupal-link-system-path=\"node/4049\">Agrimensura</a>\n"
      + "              <a href=\"https://www.fing.edu.uy/inco\" title=\"Computación\" class=\"dropdown-item\">Computación</a>\n"
      + "              <a href=\"/index.php/es/catedras/disi\" class=\"dropdown-item\" data-drupal-link-system-path=\"node/39434\">Departamento de Inserción Social del Ingeniero</a>\n"
      + "              <a href=\"/index.php/es/iet\" title=\"IET\" class=\"dropdown-item\" data-drupal-link-system-path=\"node/39444\">Estructuras y Transporte</a>\n"
      + "              <a href=\"/index.php/es/iem\" class=\"dropdown-item\" data-drupal-link-system-path=\"node/48238\">Ensayo de Materiales</a>\n"
      + "              <a href=\"/index.php/es/if\" title=\"Física\" class=\"dropdown-item\" data-drupal-link-system-path=\"node/4273\">Física</a>\n"
      + "              <a href=\"https://iie.fing.edu.uy\" title=\"Ingeniería Eléctrica\" class=\"dropdown-item\">Ingeniería Eléctrica</a>\n"
      + "              <a href=\"/index.php/es/iimpi\" class=\"dropdown-item\" data-drupal-link-system-path=\"node/45237\">Ingeniería Mecánica y Producción Industrial</a>\n"
      + "              <a href=\"/index.php/es/iiq\" title=\"Ing. Química\" class=\"dropdown-item\" data-drupal-link-system-path=\"node/23925\">Ingeniería Química</a>\n"
      + "              <a href=\"https://www.fing.edu.uy/imerl\" title=\"Matemática y Estadística\" class=\"dropdown-item\">Matemática y Estadística</a>\n"
      + "              <a href=\"https://www.fing.edu.uy/imfia\" title=\"Mecánica de los Fluidos e Ingenieria Ambiental\" class=\"dropdown-item\">Mecánica de los Fluidos e Ingenieria Ambiental</a>\n"
      + "  </div>\n"
      + "                              </li>\n"
      + "                      \n"
      + "                \n"
      + "        <li class=\"nav-item dropdown\">\n"
      + "                      <a href=\"/index.php/es/ensenanza\" title=\"Enseñanza\" class=\"nav-link dropdown-toggle\" data-bs-toggle=\"dropdown\" data-drupal-link-system-path=\"node/3084\">Enseñanza</a>\n"
      + "                          <div class=\"dropdown-menu\">\n"
      + "              <a href=\"/index.php/es/bedelia\" class=\"dropdown-item\" data-drupal-link-system-path=\"node/3295\">Bedelía</a>\n"
      + "              <a href=\"/index.php/es/ensenanza/carreras-de-grado-old\" title=\"Carreras de Grado\" class=\"dropdown-item\" data-drupal-link-system-path=\"node/25005\">Carreras de grado</a>\n"
      + "              <a href=\"https://www.fing.edu.uy/ensenanza/carrerasinterior\" class=\"dropdown-item\">Carreras en el Interior</a>\n"
      + "              <a href=\"/index.php/es/ensenanza/espacio-de-orientaci%C3%B3n-y-consulta\" class=\"dropdown-item\" data-drupal-link-system-path=\"node/7969\">Orientación y consulta</a>\n"
      + "              <a href=\"/index.php/es/posgrado\" title=\"Unidad de Posgrado\" class=\"dropdown-item\" data-drupal-link-system-path=\"node/9162\">Posgrado y Educación Permanente</a>\n"
      + "              <a href=\"/index.php/es/biblioteca\" title=\"Biblioteca\" class=\"dropdown-item\" data-drupal-link-system-path=\"node/9907\">Biblioteca</a>\n"
      + "              <a href=\"/index.php/es/uefi\" title=\"Unidad de Enseñanza\" class=\"dropdown-item\" data-drupal-link-system-path=\"node/24758\">Unidad de Enseñanza</a>\n"
      + "              <a href=\"/index.php/es/go/sitio-de-eva\" title=\"Sitio de EVA\" class=\"dropdown-item\" data-drupal-link-system-path=\"node/6685\">Sitio de EVA</a>\n"
      + "              <a href=\"/index.php/es/ensenanza/generacion-de-ingreso\" class=\"dropdown-item\" data-drupal-link-system-path=\"node/45475\">Generación de ingreso</a>\n"
      + "              <a href=\"/index.php/es/node/41254\" class=\"dropdown-item\" data-drupal-link-system-path=\"node/41254\">Futuros estudiantes</a>\n"
      + "  </div>\n"
      + "                              </li>\n"
      + "                      \n"
      + "                \n"
      + "        <li class=\"nav-item dropdown\">\n"
      + "                      <a href=\"/index.php/es/extension\" class=\"nav-link dropdown-toggle\" data-bs-toggle=\"dropdown\" data-drupal-link-system-path=\"node/33672\">Extensión</a>\n"
      + "                          <div class=\"dropdown-menu\">\n"
      + "              <a href=\"/index.php/es/node/39412\" title=\"Presentación\" class=\"dropdown-item\" data-drupal-link-system-path=\"node/39412\">Presentación</a>\n"
      + "              <a href=\"/index.php/es/extension/cometidos\" title=\"Cometidos\" class=\"dropdown-item\" data-drupal-link-system-path=\"node/3094\">Cometidos</a>\n"
      + "              <a href=\"/index.php/es/extensi%C3%B3n/actividades\" class=\"dropdown-item\" data-drupal-link-system-path=\"node/4152\">Actividades</a>\n"
      + "              <a href=\"/index.php/es/extension/asesoramiento\" title=\"Asesoramiento\" class=\"dropdown-item\" data-drupal-link-system-path=\"node/3097\">Asesoramiento</a>\n"
      + "              <a href=\"/index.php/es/extension/materiales-de-cursos\" class=\"dropdown-item\" data-drupal-link-system-path=\"node/3161\">Materiales de cursos</a>\n"
      + "              <a href=\"/index.php/es/node/40540\" class=\"dropdown-item\" data-drupal-link-system-path=\"node/40540\">Cajón de Ideas</a>\n"
      + "              <a href=\"/index.php/es/extension/llamados\" title=\"Llamados\" class=\"dropdown-item\" data-drupal-link-system-path=\"node/3098\">Llamados</a>\n"
      + "  </div>\n"
      + "                              </li>\n"
      + "                      \n"
      + "                \n"
      + "        <li class=\"nav-item dropdown\">\n"
      + "                      <a href=\"/index.php/es/investigacion\" title=\"Investigación\" class=\"nav-link dropdown-toggle\" data-bs-toggle=\"dropdown\" data-drupal-link-system-path=\"node/3114\">Investigación</a>\n"
      + "                          <div class=\"dropdown-menu\">\n"
      + "              <a href=\"/index.php/es/investigacion/actividades-de-la-instituci%C3%B3n\" title=\"Actividades de la Institutución\" class=\"dropdown-item\" data-drupal-link-system-path=\"node/6687\">Actividades de la Institución</a>\n"
      + "              <a href=\"/index.php/es/paginas/ciencia-y-tecnologia-en-tiempos-de-pandemia\" class=\"dropdown-item\" data-drupal-link-system-path=\"node/38233\">Proyectos contra Covid</a>\n"
      + "              <a href=\"/index.php/es/node/47602\" class=\"dropdown-item\" data-drupal-link-system-path=\"node/47602\">Servicios al medio</a>\n"
      + "              <a href=\"https://www.fing.edu.uy/es/investigacion/convenios\" class=\"dropdown-item\">Convenios</a>\n"
      + "              <a href=\"/index.php/es/csic\" class=\"dropdown-item\" data-drupal-link-system-path=\"node/4547\">CSIC</a>\n"
      + "  </div>\n"
      + "                              </li>\n"
      + "                      \n"
      + "                \n"
      + "        <li class=\"nav-item active dropdown\">\n"
      + "                      <a href=\"/index.php/es/comunicacion\" title=\"Comunicación\" class=\"nav-link dropdown-toggle\" data-bs-toggle=\"dropdown\" data-drupal-link-system-path=\"node/4413\">Comunicación</a>\n"
      + "                          <div class=\"dropdown-menu\">\n"
      + "              <a href=\"/index.php/es/node/39404\" class=\"dropdown-item\" data-drupal-link-system-path=\"node/39404\">Área de Comunicación</a>\n"
      + "              <a href=\"/index.php/es/comunicacion/noticias/archivo\" title=\"Archivo de noticias\" class=\"dropdown-item\" data-drupal-link-system-path=\"comunicacion/noticias/archivo\">Archivo de noticias</a>\n"
      + "              <a href=\"/index.php/es/eventos\" title=\"Eventos\" class=\"dropdown-item\" data-drupal-link-system-path=\"node/39747\">Eventos</a>\n"
      + "              <a href=\"/index.php/es/comunicacion/resumen-de-noticias\" class=\"dropdown-item\" data-drupal-link-system-path=\"node/40692\">Resumen de noticias</a>\n"
      + "              <a href=\"/index.php/es/node/47611\" title=\"Identidad visual 2022\" class=\"dropdown-item\" data-drupal-link-system-path=\"node/47611\">Identidad visual 2022</a>\n"
      + "              <a href=\"/index.php/es/comunicacion/divulgacion\" class=\"dropdown-item\" data-drupal-link-system-path=\"node/35268\">Divulgación</a>\n"
      + "              <a href=\"/index.php/es/comunicacion/convocatorias-y-becas-1\" title=\"Convocatorias y Becas\" class=\"dropdown-item\" data-drupal-link-system-path=\"node/5480\">Convocatorias y becas</a>\n"
      + "              <a href=\"/index.php/es/comunicacion/publicaciones\" title=\"Publicaciones\" class=\"dropdown-item\" data-drupal-link-system-path=\"node/4428\">Publicaciones</a>\n"
      + "              <a href=\"/index.php/es/comunicacion/galerias\" title=\"Galería de Imágenes\" class=\"dropdown-item\" data-drupal-link-system-path=\"node/6061\">Galerías de fotos</a>\n"
      + "              <a href=\"/index.php/es/llamados\" title=\"Llamados a concurso\" class=\"dropdown-item\" data-drupal-link-system-path=\"llamados\">Llamados a concurso</a>\n"
      + "              <a href=\"/index.php/es/ciclodecharlas\" class=\"dropdown-item\" data-drupal-link-system-path=\"node/11982\">Visitas y charlas</a>\n"
      + "              <a href=\"/index.php/es/comunicacion/faq\" title=\"Preguntas frecuentes\" class=\"dropdown-item\" data-drupal-link-system-path=\"node/39430\">Preguntas frecuentes</a>\n"
      + "              <a href=\"/index.php/es/telefonos\" class=\"dropdown-item active\" data-drupal-link-system-path=\"node/3186\">Teléfonos</a>\n"
      + "              <a href=\"/index.php/es/contacto\" title=\"Form de contacto\" class=\"dropdown-item\" data-drupal-link-system-path=\"webform/contacto_fing\">Contacto</a>\n"
      + "  </div>\n"
      + "                              </li>\n"
      + "            </ul>\n"
      + "\n"
      + "\n"
      + "      \n"
      + "  </div>\n"
      + "\n"
      + "\n"
      + "        </div>\n"
      + "          \n"
      + "                </div>\n"
      + "\n"
      + "      </div>\n"
      + "  </nav>\n"
      + "\n"
      + "  <main class=\"pt-5 pb-5\">\n"
      + "    \n"
      + "          <div class=\"page__content\">\n"
      + "        <div class=\"container\">\n"
      + "          <div class=\"row\">\n"
      + "            <div class=\"col-sm-3\">  \n"
      + "  <div class=\"block--booknavigation block block--fing2-booknavigation\">\n"
      + "\n"
      + "  \n"
      + "    \n"
      + "\n"
      + "            \n"
      + "              <ul>\n"
      + "              <li>\n"
      + "        <a href=\"/es/comunicacion/publicaciones\" hreflang=\"es\">Publicaciones</a>\n"
      + "              </li>\n"
      + "          <li>\n"
      + "        <a href=\"/es/comunicacion/convocatorias-y-becas-1\" hreflang=\"es\">Convocatorias y Becas</a>\n"
      + "              </li>\n"
      + "          <li>\n"
      + "        <a href=\"/es/comunicacion/divulgacion\" hreflang=\"es\">Divulgación</a>\n"
      + "              </li>\n"
      + "          <li>\n"
      + "        <a href=\"/es/eventos\" hreflang=\"es\">Eventos</a>\n"
      + "              </li>\n"
      + "          <li>\n"
      + "        <a href=\"/es/comunicacion/faq\" hreflang=\"es\">Preguntas Frecuentes</a>\n"
      + "              </li>\n"
      + "          <li>\n"
      + "        <a href=\"/es/comunicacion/resumen-de-noticias\" hreflang=\"es\">Resumen de noticias</a>\n"
      + "              </li>\n"
      + "          <li>\n"
      + "        <a href=\"/es/comunicacion/galerias\" hreflang=\"es\">Multimedia</a>\n"
      + "              </li>\n"
      + "          <li>\n"
      + "        <a href=\"/es/go/llamados-concurso\" hreflang=\"es\">Llamados a Concurso</a>\n"
      + "              </li>\n"
      + "          <li>\n"
      + "        <a href=\"/es/node/47611\" hreflang=\"es\">Identidad visual</a>\n"
      + "              </li>\n"
      + "          <li>\n"
      + "        <a href=\"/es/telefonos\" hreflang=\"es\">Teléfonos</a>\n"
      + "              </li>\n"
      + "          <li>\n"
      + "        <a href=\"/es/go/contacto\" hreflang=\"es\">Contacto</a>\n"
      + "              </li>\n"
      + "        </ul>\n"
      + "  \n"
      + "\n"
      + "\n"
      + "      \n"
      + "  </div>\n"
      + "\n"
      + "</div>                                                              <div class=\"col-sm-9\">   <div data-drupal-messages-fallback class=\"hidden\"></div>\n"
      + "  <div class=\"block--breadcrumbs block block--fing2-breadcrumbs\">\n"
      + "\n"
      + "  \n"
      + "    \n"
      + "\n"
      + "              <nav aria-label=\"breadcrumb\" class=\"\">\n"
      + "    <ol class=\"breadcrumb\">\n"
      + "              <li class=\"breadcrumb-item \">\n"
      + "                      <a href=\"/es\">Inicio</a>\n"
      + "                  </li>\n"
      + "          </ol>\n"
      + "  </nav>\n"
      + "\n"
      + "      \n"
      + "  </div>\n"
      + "\n"
      + "  <div class=\"block--pagetitle block block--fing2-pagetitle\">\n"
      + "\n"
      + "  \n"
      + "    \n"
      + "\n"
      + "            \n"
      + "\n"
      + "\n"
      + "  \n"
      + "\n"
      + "\n"
      + "  <h1  class=\"page-title\">\n"
      + "                  \n"
      + "<span>Teléfonos</span>\n"
      + "\n"
      + "            </h1>\n"
      + "\n"
      + "\n"
      + "      \n"
      + "  </div>\n"
      + "\n"
      + "  <div class=\"block--mainpagecontent block block--fing2-mainpagecontent block--system-main\">\n"
      + "\n"
      + "  \n"
      + "    \n"
      + "\n"
      + "            <article class=\"node book book--full\">\n"
      + "  \n"
      + "  \n"
      + "\n"
      + "      \n"
      + "            <div class=\"field field--name-body field--type-text-with-summary field--label-hidden field__item\"><p>La Facultad se encuentra en un proceso gradual de instalación de telefonía IP en toda la institución que sustituirá la red convencional y, por ende, los números de marcado.<br>\n"
      + "Actualmente, los teléfonos que se mudaron a la nueva modalidad son los correspondientes a los Servicios Administrativos y los Intitutos que se muestran en el listado de <span style=\"color: #3366ff;\">color azul.</span></p>\n"
      + "<p>El instructivo para utilizar los nuevos teléfonos IP puede descargarse haciendo <strong><a href=\"https://www.fing.edu.uy/sites/default/files/2011/3186/telefonia_ip_instructivo_de_operacion_V1.pdf\" target=\"_blank\">clic aquí.</a></strong></p>\n"
      + "<p><span style=\"color: #000000;\">Mesa Central</span><br>\n"
      + "<span style=\"color: #3366ff;\">2714 2714 int. 10100</span></p>\n"
      + "<p><span style=\"color: #000000;\"><strong>Decanato</strong></span><br>\n"
      + "<span style=\"color: #3366ff;\"><span style=\"color: #3366ff;\"><span style=\"color: #808080;\"><span style=\"color: #000000;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Secretaría de Decanato</span></span></span><br>\n"
      + "<span style=\"color: #3366ff;\"><span style=\"color: #808080;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span>2714 2714 int. 10119<br>\n"
      + "<span style=\"color: #808080;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <em>&nbsp;</em><span style=\"color: #000000;\">Asistentes Académicos</span></span><br>\n"
      + "<span style=\"color: #3366ff;\"><span style=\"color: #3366ff;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <em><span style=\"color: #000000;\"><strong>&nbsp;</strong></span></em></span>2714 2714 int. 10221<br>\n"
      + "&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;&nbsp;</span></span>Área de Comunicación<em> </em><br>\n"
      + "&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<span style=\"color: #3366ff;\">2714 2714 int. 10122</span></p>\n"
      + "<p>&nbsp;</p>\n"
      + "<p><strong>División Secretaría</strong><br>\n"
      + "<span style=\"color: #3366ff;\">2714 2714 int. 10118</span></p>\n"
      + "<p style=\"padding-left: 30px;\"><span style=\"color: #000000;\"><strong>Departamento de Bedelía</strong></span><br>\n"
      + "<span style=\"color: #3366ff;\">2714 2714 int. 10113</span><br>\n"
      + "<span style=\"color: #808080;\"><strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </strong></span><span style=\"color: #000000;\"><em>Posgrados </em></span><br>\n"
      + "<strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </strong><span style=\"color: #3366ff;\">2714 2714 int. 10163</span></p>\n"
      + "<p style=\"padding-left: 30px;\"><span style=\"color: #3366ff;\"><span style=\"color: #000000;\"><strong>Departamento de Biblioteca</strong></span><br>\n"
      + "<span style=\"color: #3366ff;\">2714 2714 int. 10133</span></span></p>\n"
      + "<p style=\"padding-left: 30px;\"><strong><span style=\"color: #000000;\">Departamento de Cogobierno </span></strong><br>\n"
      + "<span style=\"color: #000000;\"><em>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Sección Consejo</em></span><br>\n"
      + "<strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </strong><span style=\"color: #3366ff;\">2714 2714 int. 10116</span><br>\n"
      + "&nbsp;<span style=\"color: #000000;\"><em>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Sección Comisiones y Claustro</em></span><br>\n"
      + "<strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </strong><span style=\"color: #3366ff;\">2714 2714 int. 10135</span></p>\n"
      + "<p style=\"padding-left: 30px;\"><span style=\"color: #000000;\"><strong>Departamento de Compras - Suministros</strong></span><br>\n"
      + "<span style=\"color: #3366ff;\">2714 2714 int. 10115<br>\n"
      + "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color: #000000;\"><em>&nbsp;&nbsp;&nbsp;&nbsp; Proveduría</em></span><br>\n"
      + "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style=\"color: #000000;\">2711 0698 int. 144</span></span></p>\n"
      + "<p style=\"padding-left: 30px;\"><span style=\"color: #000000;\"><strong>Departamento de Intendencia</strong></span><br>\n"
      + "<span style=\"color: #3366ff;\">2714 2714 int. 10150</span><br>\n"
      + "<strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </strong>&nbsp;<span style=\"color: #000000;\"><em>Servicio de Apoyo&nbsp;</em></span><br>\n"
      + "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style=\"color: #3366ff;\">2714 2714 int. 10154</span></p>\n"
      + "<p style=\"padding-left: 30px;\"><span style=\"color: #000000;\"><strong>Departamento de Recursos Humanos</strong></span><br>\n"
      + "<span style=\"color: #3366ff;\">2714 2714 int. 10111</span></p>\n"
      + "<p style=\"padding-left: 30px;\"><strong><span style=\"color: #000000;\">Departamento de Secretaría</span></strong><br>\n"
      + "<span style=\"color: #3366ff;\">2714 2714 int. 10118 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>\n"
      + "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <em><span style=\"color: #000000;\">Mesa de Entrada</span></em><br>\n"
      + "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2714 2714 int. 10131</span></p>\n"
      + "<p style=\"padding-left: 30px;\"><strong>Archivo de la Facultad de Ingeniería</strong><br>\n"
      + "<span style=\"color: #3366ff;\">2714 2714 int. 10160</span></p>\n"
      + "<p><span style=\"color: #000000;\"><strong>División Contaduría</strong></span><br>\n"
      + "<span style=\"color: #000000;\"><em>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Tesorería</em></span><br>\n"
      + "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style=\"color: #3366ff;\">2714 2714 int. 10110</span><br>\n"
      + "<span style=\"color: #000000;\"><em>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Sueldos</em></span><br>\n"
      + "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style=\"color: #3366ff;\">2714 2714 int. 10121</span><br>\n"
      + "<em>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Facturación</em><br>\n"
      + "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style=\"color: #3366ff;\">2714 2714 int. 10189</span><br>\n"
      + "<span style=\"color: #000000;\"><em>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Extra-presupuesto</em></span><br>\n"
      + "<span style=\"color: #3366ff;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span><span style=\"color: #3366ff;\"><span style=\"color: #3366ff;\">2714 2714 int. 10145</span></span><br>\n"
      + "<strong><span style=\"color: #3366ff;\"><span style=\"color: #3366ff;\">&nbsp;&nbsp;&nbsp;&nbsp;</span></span></strong><span style=\"color: #000000;\"><em>&nbsp;&nbsp;&nbsp; Gastos presupuesto</em></span><br>\n"
      + "<strong><span style=\"color: #3366ff;\"><span style=\"color: #3366ff;\">&nbsp;&nbsp;&nbsp;</span></span></strong><span style=\"color: #3366ff;\"><span style=\"color: #3366ff;\">&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span style=\"color: #3366ff;\"><span style=\"color: #3366ff;\"><span style=\"color: #3366ff;\">2714 2714 int. 10146</span></span></span><br>\n"
      + "Atención: lun, mar, jue y vie de 9:00 a 12:00 - miércoles 8:30 a 13:00</p>\n"
      + "<p>\n"
      + "<span style=\"color: #000000;\"><strong>Asesor Legal</strong></span><br>\n"
      + "<span style=\"color: #3366ff;\">2714 2714 int. 10162</span></p>\n"
      + "<p><span style=\"color: #000000;\"><strong>Cantina (Edificio Central - Piso 0)</strong></span><br>\n"
      + "<span style=\"color: #3366ff;\">2714 2714 int.10139</span></p>\n"
      + "<p><span style=\"color: #000000;\"><strong>Coordinación de la carrera Tecnólogo Mecánico</strong></span><br>\n"
      + "<span style=\"color: #3366ff;\">2714 2714 int.10159</span></p>\n"
      + "<p><span style=\"color: #3366ff;\"><span style=\"color: #000000;\"><strong>Espacio de Orientación y Consulta</strong></span><br>\n"
      + "<span style=\"color: #3366ff;\">2714 2714 int. 10220</span><br>\n"
      + "<a href=\"http://www.fing.edu.uy/ensenanza/espacio-de-orientaci%C3%B3n-y-consulta\" target=\"_blank\">http://www.fing.edu.uy/ensenanza/espacio-de-orientaci%C3%B3n-y-consulta</a></span></p>\n"
      + "<p><span style=\"color: #000000;\"><strong>Plan de Obras</strong></span><br>\n"
      + "<span style=\"color: #3366ff;\">2714 2714 int. 10137</span></p>\n"
      + "<p><span style=\"color: #000000;\"><span style=\"color: #000000;\"><strong>Polifuncional \"José Luis Massera\"</strong></span><br>\n"
      + "<span style=\"color: #3366ff;\"><span style=\"color: #3366ff;\">2714 2714 int. 10400</span></span></span></p>\n"
      + "<p><span style=\"color: #000000;\"><strong>Unidad de Recursos Informáticos</strong></span><br>\n"
      + "<span style=\"color: #000000;\"><span style=\"color: #3366ff;\"><span style=\"color: #3366ff;\">2714 2714 int. 10157</span></span></span><br>\n"
      + "<a class=\"moz-txt-link-freetext\" href=\"https://www.fing.edu.uy/sysadmin\">https://www.fing.edu.uy/sysadmin</a></p>\n"
      + "<p><span style=\"color: #3366ff;\"><strong><span style=\"color: #000000;\">Unidad de Enseñanza</span></strong><br>\n"
      + "<span style=\"color: #3366ff;\">2714 2714 int. 10152</span><br>\n"
      + "<a href=\"https://www.fing.edu.uy/uefi\" target=\"_blank\"><span style=\"color: #000000;\">https://www.fing.edu.uy/uefi</span></a><br>\n"
      + "&nbsp;<br>\n"
      + "<span style=\"color: #000000;\"><strong>Unidad de Extensión</strong></span></span><br>\n"
      + "<span style=\"color: #3366ff;\"><span style=\"color: #3366ff;\"><span style=\"color: #3366ff;\">2714 2714 int. 10301</span></span></span><br>\n"
      + "<a href=\"https://www.fing.edu.uy/extension\" target=\"_blank\">https://www.fing.edu.uy/extension</a><br>\n"
      + "<strong>&nbsp;</strong></p>\n"
      + "<p>\n"
      + "<strong>Asociación de Docente de la Facultad de Ingeniería (ADFI)</strong><br>\n"
      + "<span style=\"color: #3366ff;\">2714 2714 int. 10161</span></p>\n"
      + "<p><strong>Centro de Estudiantes de Ingeniería</strong><br>\n"
      + "<em>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Fotocopiadora</em><br>\n"
      + "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style=\"color: #3366ff;\">2714 2714 int. 10020&nbsp;</span><br>\n"
      + "<em><strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </strong><span style=\"color: #000000;\">Oficina de Trabajo</span></em><br>\n"
      + "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style=\"color: #3366ff;\">2714 2714 int. 10020&nbsp;</span><br>\n"
      + "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <em>Sala de Reuniones</em><br>\n"
      + "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style=\"color: #3366ff;\">2714 2714 int. 10024</span></p>\n"
      + "<p>&nbsp;</p>\n"
      + "<p><strong>Instituto de Agrimensura</strong><br>\n"
      + "<span style=\"color: #3366ff;\">2714 2714 int.13100</span><br>\n"
      + "<a href=\"http://www.fing.edu.uy/ia\" target=\"_blank\">http://www.fing.edu.uy/ia</a></p>\n"
      + "<p>\n"
      + "<strong>Instituto de Computación</strong><br>\n"
      + "<span style=\"color: #3366ff;\">2714 2714 int.12100&nbsp;</span><br>\n"
      + "<a href=\"http://www.fing.edu.uy/inco\" target=\"_self\">http://www.fing.edu.uy/inco</a></p>\n"
      + "<p><strong>Instituto de Computación Cuerpo Norte</strong><br>\n"
      + "2712 29 90</p>\n"
      + "<p><strong>Instituto de Física</strong><br>\n"
      + "<span style=\"color: #3366ff;\">2714 2714 int.15100</span><br>\n"
      + "<a href=\"http://www.fing.edu.uy/if\" target=\"_self\">http://www.fing.edu.uy/if</a><br>\n"
      + "&nbsp;<br>\n"
      + "<strong>Instituto de Ingeniería Eléctrica \"Prof. Ing. Agustín Cisa\"</strong><br>\n"
      + "<span style=\"color: #3366ff;\">2714 2714 int. 11100</span><br>\n"
      + "<a href=\"http://iie.fing.edu.uy\" target=\"_self\">http://iie.fing.edu.uy</a><br>\n"
      + "&nbsp;<br>\n"
      + "<strong>Instituto de Ensayo de Materiales</strong><br>\n"
      + "<span style=\"color: #3366ff;\">2714 2714 int. 16100</span><br>\n"
      + "<a href=\"http://www.fing.edu.uy/iem\" target=\"_self\">http://www.fing.edu.uy/iem</a><br>\n"
      + "&nbsp;<br>\n"
      + "<strong>Instituto de Estructuras y Transporte \"Prof. Ing. Julio Ricaldoni\"</strong><br>\n"
      + "<span style=\"color: #3366ff;\">2714 2714 int. 14100</span><br>\n"
      + "<a href=\"http://www.fing.edu.uy/iet\" target=\"_self\">http://www.fing.edu.uy/iet</a><br>\n"
      + "&nbsp;<br>\n"
      + "<strong>Instituto de Matemática y Estadística \"Prof. Ing. Rafael Laguardia\"</strong><br>\n"
      + "<span style=\"color: #3366ff;\">2714 2714 int.&nbsp; 19100 y 19101</span><br>\n"
      + "<a href=\"http://www.fing.edu.uy/imerl\" target=\"_self\">http://www.fing.edu.uy/imerl</a><br>\n"
      + "&nbsp;<br>\n"
      + "<strong>Instituto de Ingeniería Mecánica y Producción Industrial</strong><br>\n"
      + "<span style=\"color: #3366ff;\">2714 2714 int. 17100</span><br>\n"
      + "<a href=\"http://www.fing.edu.uy/iimpi\" target=\"_self\">http://www.fing.edu.uy/iimpi</a><br>\n"
      + "&nbsp;<br>\n"
      + "<strong>Instituto de Mecánica de los Fluidos e Ing. Ambiental \"Prof. Ing. Oscar Maggiolo\"</strong><br>\n"
      + "<span style=\"color: #3366ff;\">2714 2714 int. 20200 y 20201&nbsp;</span><br>\n"
      + "<a href=\"http://www.fing.edu.uy/imfia\" target=\"_blank\">http://www.fing.edu.uy/imfia</a><br>\n"
      + "&nbsp;<br>\n"
      + "<strong>Instituto de Ingeniería Química</strong><br>\n"
      + "<span style=\"color: #3366ff;\">2714 2714 int. 18100</span><br>\n"
      + "<a href=\"http://www.fing.edu.uy/iiq\" target=\"_self\">http://www.fing.edu.uy/iiq</a><br>\n"
      + "&nbsp;<br>\n"
      + "<strong>Departamento de Inserción Social del Ingeniero</strong><br>\n"
      + "<span style=\"color: #3366ff;\">2714 2714 int. 10300</span><br>\n"
      + "<a href=\"http://www.fing.edu.uy/catedras/disi\" target=\"_self\">http://www.fing.edu.uy/catedras/disi</a></p>\n"
      + "<p style=\"padding-left: 30px;\"><em>Arquitectura Tecnológica</em><br>\n"
      + "<span style=\"color: #3366ff;\">2714 2714 int. 10302</span></p>\n"
      + "</div>\n"
      + "      \n"
      + "      <div class=\"field field--name-upload field--type-file field--label-hidden field__items\">\n"
      + "              <div class=\"field__item\"><span class=\"file file--mime-application-pdf file--application-pdf\"><a href=\"/sites/default/files/2011/3186/telefonia_ip_instructivo_de_operacion_V1.pdf\" type=\"application/pdf\" title=\"telefonia_ip_instructivo_de_operacion_V1.pdf\">telefonia_ip_instructivo_de_operacion_V1.pdf</a></span>\n"
      + "  <span>(68.28 KB)</span>\n"
      + "</div>\n"
      + "          </div>\n"
      + "    <nav role=\"navigation\" aria-labelledby=\"book-label-4413\">\n"
      + "          <!--<h2 class = \"traversal_links\">Enlaces transversales de Book para Teléfonos</h2>-->\n"
      + "    \n"
      + "    <div class=\"row book_navigation\">\n"
      + "        \n"
      + "                      <div class=\"col-sm-4 izq\">\n"
      + "                \n"
      + "                  <a href=\"/es/node/47611\" rel=\"prev\" title=\"Ir a la página anterior\"><b>‹</b> Identidad visual</a>\n"
      + "                \n"
      + "            </div>\n"
      + "                                <div class=\"col-sm-4 medio\">\n"
      + "               \n"
      + "                  <a href=\"/es/comunicacion\" title=\"Ir a la página madre\">Arriba</a>\n"
      + "                \n"
      + "            </div>\n"
      + "                                <div class=\"col-sm-4 der\">\n"
      + "               \n"
      + "                  <a href=\"/es/go/contacto\" rel=\"next\" title=\"Ir a la página siguiente\">Contacto <b>›</b></a>\n"
      + "                \n"
      + "            </div>\n"
      + "                  \n"
      + "    </div>\n"
      + "    \n"
      + "            <div clas = \"book_tree\">\n"
      + "      \n"
      + "    </div>\n"
      + "  </nav>\n"
      + "\n"
      + "  </article>\n"
      + "\n"
      + "      \n"
      + "  </div>\n"
      + "\n"
      + "</div>\n"
      + "                                  </div>\n"
      + "        </div>\n"
      + "      </div>\n"
      + "      </main>\n"
      + "\n"
      + "      <footer class=\"page__footer\">\n"
      + "      <div class=\"container\">\n"
      + "        <div class=\"row\">\n"
      + "            <div class=\"col-sm-3\">  \n"
      + "  <div class=\"block--estudiantes block block--fing2-estudiantes block--system-menu\">\n"
      + "\n"
      + "  \n"
      + "            <h2>Estudiantes</h2>\n"
      + "        \n"
      + "\n"
      + "            \n"
      + "  \n"
      + "\n"
      + "\n"
      + "  <ul class=\"nav\">\n"
      + "                          \n"
      + "                \n"
      + "        <li class=\"nav-item\">\n"
      + "                      <a href=\"/es/node/41254\" title=\"Generacion de ingreso\" class=\"nav-link\" data-drupal-link-system-path=\"node/41254\">Futuros estudiantes</a>\n"
      + "                  </li>\n"
      + "                      \n"
      + "                \n"
      + "        <li class=\"nav-item\">\n"
      + "                      <a href=\"/es/ensenanza/carreras-de-grado-old\" title=\"Carreras\" class=\"nav-link\" data-drupal-link-system-path=\"node/25005\">Carreras</a>\n"
      + "                  </li>\n"
      + "                      \n"
      + "                \n"
      + "        <li class=\"nav-item\">\n"
      + "                      <a href=\"https://eva.fing.edu.uy/\" title=\"EVA\" class=\"nav-link\">EVA</a>\n"
      + "                  </li>\n"
      + "                      \n"
      + "                \n"
      + "        <li class=\"nav-item\">\n"
      + "                      <a href=\"/es/bedelia\" title=\"Bedelia\" class=\"nav-link\" data-drupal-link-system-path=\"node/3295\">Bedelia</a>\n"
      + "                  </li>\n"
      + "                      \n"
      + "                \n"
      + "        <li class=\"nav-item\">\n"
      + "                      <a href=\"/es/bedelia/horarios\" title=\"Horarios\" class=\"nav-link\" data-drupal-link-system-path=\"node/3820\">Horarios</a>\n"
      + "                  </li>\n"
      + "                      \n"
      + "                \n"
      + "        <li class=\"nav-item\">\n"
      + "                      <a href=\"/es/ensenanza/espacio-de-orientaci%C3%B3n-y-consulta\" title=\"Espacio de orientación\" class=\"nav-link\" data-drupal-link-system-path=\"node/7969\">Espacio de orientación</a>\n"
      + "                  </li>\n"
      + "                      \n"
      + "                \n"
      + "        <li class=\"nav-item\">\n"
      + "                      <a href=\"/es/noticias/area-de-comunicacion/llevate-la-fing-en-el-bolsillo\" title=\"App de grado\" class=\"nav-link\" data-drupal-link-system-path=\"node/26775\">App de grado</a>\n"
      + "                  </li>\n"
      + "                      \n"
      + "                \n"
      + "        <li class=\"nav-item\">\n"
      + "                      <a href=\"/es/ensenanza/espacio-de-orientaci%C3%B3n-y-consulta/procedimientos-para-solicitudes\" title=\"Reválidas y trámites\" class=\"nav-link\" data-drupal-link-system-path=\"node/30121\">Reválidas y trámites</a>\n"
      + "                  </li>\n"
      + "                      \n"
      + "                \n"
      + "        <li class=\"nav-item\">\n"
      + "                      <a href=\"/es/comunicacion/becas\" title=\"Becas intercambio\" class=\"nav-link\" data-drupal-link-system-path=\"node/6034\">Becas intercambio</a>\n"
      + "                  </li>\n"
      + "                      \n"
      + "                \n"
      + "        <li class=\"nav-item\">\n"
      + "                      <a href=\"https://www.fing.edu.uy/es/node/38278\" class=\"nav-link\">Actuación contra acoso</a>\n"
      + "                  </li>\n"
      + "            </ul>\n"
      + "\n"
      + "\n"
      + "      \n"
      + "  </div>\n"
      + "\n"
      + "</div>\n"
      + "            <div class=\"col-sm-3\">  \n"
      + "  <div class=\"block--docentes block block--fing2-docentes block--system-menu\">\n"
      + "\n"
      + "  \n"
      + "            <h2>Docentes</h2>\n"
      + "        \n"
      + "\n"
      + "            \n"
      + "  \n"
      + "\n"
      + "\n"
      + "  <ul class=\"nav\">\n"
      + "                          \n"
      + "                \n"
      + "        <li class=\"nav-item\">\n"
      + "                      <a href=\"/es/comunicacion/convocatorias\" title=\"Convocatorias financiables\" class=\"nav-link\" data-drupal-link-system-path=\"node/6035\">Convocatorias financiables</a>\n"
      + "                  </li>\n"
      + "                      \n"
      + "                \n"
      + "        <li class=\"nav-item\">\n"
      + "                      <a href=\"/es/comunicacion/becas\" title=\"Becas posgrado\" class=\"nav-link\" data-drupal-link-system-path=\"node/6034\">Becas posgrado</a>\n"
      + "                  </li>\n"
      + "                      \n"
      + "                \n"
      + "        <li class=\"nav-item\">\n"
      + "                      <a href=\"/es/llamados\" class=\"nav-link\" data-drupal-link-system-path=\"llamados\">Llamados abiertos</a>\n"
      + "                  </li>\n"
      + "                      \n"
      + "                \n"
      + "        <li class=\"nav-item\">\n"
      + "                      <a href=\"/intranet/marcas\" title=\"Marcas horarias\" class=\"nav-link\">Marcas horarias</a>\n"
      + "                  </li>\n"
      + "                      \n"
      + "                \n"
      + "        <li class=\"nav-item\">\n"
      + "                      <a href=\"/es/bedelia/horarios\" title=\"Horarios de clase\" class=\"nav-link\" data-drupal-link-system-path=\"node/3820\">Horarios de clase</a>\n"
      + "                  </li>\n"
      + "                      \n"
      + "                \n"
      + "        <li class=\"nav-item\">\n"
      + "                      <a href=\"https://map.udelar.edu.uy/PortalMAP/\" title=\"Recibos de sueldo\" class=\"nav-link\">Recibos de sueldo</a>\n"
      + "                  </li>\n"
      + "                      \n"
      + "                \n"
      + "        <li class=\"nav-item\">\n"
      + "                      <a href=\"/es/gestion/normas-y-reglamentos\" class=\"nav-link\" data-drupal-link-system-path=\"node/3090\">Reglamentos</a>\n"
      + "                  </li>\n"
      + "                      \n"
      + "                \n"
      + "        <li class=\"nav-item\">\n"
      + "                      <a href=\"https://www.fing.edu.uy/es/node/38278\" class=\"nav-link\">Actuación contra acoso</a>\n"
      + "                  </li>\n"
      + "            </ul>\n"
      + "\n"
      + "\n"
      + "      \n"
      + "  </div>\n"
      + "\n"
      + "</div>\n"
      + "            <div class=\"col-sm-3\">  \n"
      + "  <div class=\"block--egresados block block--fing2-egresados block--system-menu\">\n"
      + "\n"
      + "  \n"
      + "            <h2>Egresados</h2>\n"
      + "        \n"
      + "\n"
      + "            \n"
      + "  \n"
      + "\n"
      + "\n"
      + "  <ul class=\"nav\">\n"
      + "                          \n"
      + "                \n"
      + "        <li class=\"nav-item\">\n"
      + "                      <a href=\"/es/ensenanza/carreras-de-posgrado\" title=\"Carreras de posgrado\" class=\"nav-link\" data-drupal-link-system-path=\"node/25306\">Carreras de posgrado</a>\n"
      + "                  </li>\n"
      + "                      \n"
      + "                \n"
      + "        <li class=\"nav-item\">\n"
      + "                      <a href=\"/es/ensenanza/cursos-posgrado\" class=\"nav-link\" data-drupal-link-system-path=\"node/9579\">Cursos de Educación Permanente</a>\n"
      + "                  </li>\n"
      + "                      \n"
      + "                \n"
      + "        <li class=\"nav-item\">\n"
      + "                      <a href=\"https://egresados.fondodesolidaridad.edu.uy/\" title=\"Fondo de solidaridad\" class=\"nav-link\">Fondo de solidaridad</a>\n"
      + "                  </li>\n"
      + "                      \n"
      + "                \n"
      + "        <li class=\"nav-item\">\n"
      + "                      <a href=\"/es/ensenanza/espacio-de-orientaci%C3%B3n-y-consulta\" title=\"Reválidas\" class=\"nav-link\" data-drupal-link-system-path=\"node/7969\">Reválidas</a>\n"
      + "                  </li>\n"
      + "                      \n"
      + "                \n"
      + "        <li class=\"nav-item\">\n"
      + "                      <a href=\"/es/alumni\" title=\"Red Alumni\" class=\"nav-link\" data-drupal-link-system-path=\"node/33194\">Red Alumni</a>\n"
      + "                  </li>\n"
      + "                      \n"
      + "                \n"
      + "        <li class=\"nav-item\">\n"
      + "                      <a href=\"/es/institucional/organizaciones\" title=\"Asociaciones\" class=\"nav-link\" data-drupal-link-system-path=\"node/3167\">Asociaciones</a>\n"
      + "                  </li>\n"
      + "            </ul>\n"
      + "\n"
      + "\n"
      + "      \n"
      + "  </div>\n"
      + "\n"
      + "</div>\n"
      + "            <div class=\"col-sm-3\">  \n"
      + "  <div class=\"block--funcionarios block block--fing2-funcionarios block--system-menu\">\n"
      + "\n"
      + "  \n"
      + "            <h2>Funcionarios</h2>\n"
      + "        \n"
      + "\n"
      + "            \n"
      + "  \n"
      + "\n"
      + "\n"
      + "  <ul class=\"nav\">\n"
      + "                          \n"
      + "                \n"
      + "        <li class=\"nav-item\">\n"
      + "                      <a href=\"/es/gestion/formularios\" title=\"Formularios\" class=\"nav-link\" data-drupal-link-system-path=\"node/3089\">Formularios</a>\n"
      + "                  </li>\n"
      + "                      \n"
      + "                \n"
      + "        <li class=\"nav-item\">\n"
      + "                      <a href=\"/intranet/marcas\" title=\"Marcas horarias\" class=\"nav-link\">Marcas horarias</a>\n"
      + "                  </li>\n"
      + "                      \n"
      + "                \n"
      + "        <li class=\"nav-item\">\n"
      + "                      <a href=\"https://map.udelar.edu.uy/PortalMAP/\" title=\"Recibos de sueldo\" class=\"nav-link\">Recibos de sueldo</a>\n"
      + "                  </li>\n"
      + "                      \n"
      + "                \n"
      + "        <li class=\"nav-item\">\n"
      + "                      <a href=\"http://www.capacitacion.edu.uy/index.php/convocatorias\" class=\"nav-link\">Capacitación</a>\n"
      + "                  </li>\n"
      + "                      \n"
      + "                \n"
      + "        <li class=\"nav-item\">\n"
      + "                      <a href=\"/es/gestion/normas-y-reglamentos\" title=\"Reglamentos\" class=\"nav-link\" data-drupal-link-system-path=\"node/3090\">Reglamentos</a>\n"
      + "                  </li>\n"
      + "                      \n"
      + "                \n"
      + "        <li class=\"nav-item\">\n"
      + "                      <a href=\"https://www.fing.edu.uy/es/node/38278\" class=\"nav-link\">Actuación contra acoso</a>\n"
      + "                  </li>\n"
      + "                      \n"
      + "                \n"
      + "        <li class=\"nav-item\">\n"
      + "                      <a href=\"/es/node/45348\" class=\"nav-link\" data-drupal-link-system-path=\"node/45348\">Trámites de cargos docentes</a>\n"
      + "                  </li>\n"
      + "            </ul>\n"
      + "\n"
      + "\n"
      + "      \n"
      + "  </div>\n"
      + "\n"
      + "</div>\n"
      + "        </div> \n"
      + "      </div>\n"
      + "      <div class=\"container-fluid\">\n"
      + "        <div class=\"d-flex justify-content-md-between align-items-md-center\">\n"
      + "            \n"
      + "  <div class=\"container-fluid block--pie block--type-basic block block--basic block--fing2-pie\">\n"
      + "\n"
      + "  \n"
      + "    \n"
      + "\n"
      + "            \n"
      + "            <div class=\"field field--name-body field--type-text-with-summary field--label-hidden field__item\"><p>Julio Herrera y Reissig 565 - Montevideo - Uruguay</p>\n"
      + "<p><a href=\"https://www.facebook.com/fingudelar/\" target=\"_blank\"><img src=\"/sites/default/files/inline-images/icono_fb.png\" data-entity-uuid=\"1001ea1e-a2ff-41ef-817c-a85090f29154\" data-entity-type=\"file\" alt=\"Facebook\" width=\"48\" height=\"48\"></a> <a href=\"https://www.instagram.com/fingudelar/\" target=\"_blank\"><img src=\"/sites/default/files/inline-images/icono_ig.png\" data-entity-uuid=\"de55f1fe-1736-418c-8979-c9b7ab0bc117\" data-entity-type=\"file\" alt=\"instagram\" width=\"48\" height=\"48\"></a> <a href=\"https://www.youtube.com/channel/UCO3517jcMuX6DSuMlXSU5Ww\" target=\"_blank\"><img src=\"/sites/default/files/inline-images/icono_yt.png\" data-entity-uuid=\"73a7a74c-ceb7-4990-a17b-73c088b946d5\" data-entity-type=\"file\" alt=\"Youtube\" width=\"48\" height=\"48\"></a> <a href=\"https://open.spotify.com/show/7fko35hhu10usvi19VlHt5?si=7uzo6TKFTSOy42mb74_mSw\" target=\"_blank\"><img src=\"/sites/default/files/inline-images/icono_spotify.png\" data-entity-uuid=\"a7207377-83b7-4116-8609-53e87fc511d4\" data-entity-type=\"file\" alt=\"Spotify\" width=\"48\" height=\"48\"> </a><a href=\"https://www.linkedin.com/company/fingudelar\" data-entity-type=\"file\" data-entity-uuid=\"8627a86a-ad0d-4f3a-af22-0a7606269f6f\"><img src=\"/sites/default/files/inline-images/icono_linkedin.png\" data-entity-uuid=\"c52e5aa4-d5dd-4738-bbbd-691ea0ec89bb\" data-entity-type=\"file\" alt=\"Linkedin\" width=\"48\" height=\"48\"></a> <a href=\"/noticias/rssfeed\" data-entity-type=\"file\" data-entity-uuid=\"8627a86a-ad0d-4f3a-af22-0a7606269f6f\"><img src=\"/sites/default/files/inline-images/icono_rss_0.png\" data-entity-uuid=\"32d98fa0-ab6a-4d05-93fd-0a720a22dd24\" data-entity-type=\"file\" width=\"48\" height=\"48\"></a></p>\n"
      + "</div>\n"
      + "      \n"
      + "      \n"
      + "  </div>\n"
      + "\n"
      + "\n"
      + "        </div>\n"
      + "      </div>\n"
      + "    </footer>\n"
      + "  </div>\n"
      + "\n"
      + "  </div>\n"
      + "\n"
      + "    \n"
      + "    <script type=\"application/json\" data-drupal-selector=\"drupal-settings-json\">{\"path\":{\"baseUrl\":\"\\/\",\"pathPrefix\":\"es\\/\",\"currentPath\":\"node\\/3186\",\"currentPathIsAdmin\":false,\"isFront\":false,\"currentLanguage\":\"es\",\"themeUrl\":\"themes\\/custom\\/fing2\",\"currentQuery\":{\"q\":\"es\\/telefonos\"}},\"pluralDelimiter\":\"\\u0003\",\"suppressDeprecationErrors\":true,\"matomo\":{\"disableCookies\":false,\"trackMailto\":true,\"trackColorbox\":true},\"ckeditorAccordion\":{\"accordionStyle\":{\"collapseAll\":1,\"keepRowsOpen\":1,\"animateAccordionOpenAndClose\":1,\"openTabsWithHash\":0}},\"ajaxTrustedUrl\":{\"\\/es\\/search\\/node\":true},\"user\":{\"uid\":0,\"permissionsHash\":\"949f699a7d56fead9d532bcda5d8bdb2f4da636dee3e21bd13e38f0a699bb98a\"}}</script>\n"
      + "<script src=\"/sites/default/files/js/js_PppLDq75BRCQlt-IHteZp7Obx11K5TNRRXky9o22oGs.js?scope=footer&amp;delta=0&amp;language=es&amp;theme=fing2&amp;include=eJw9zNEKgCAMheEXEge9UKw5S9IN5oh8-4Kkq_PdnJ-wsiQ0oInoBzcODV2bwjehj-7cYMPOwTCVG7qPyiEX2ZdpOjkVV1uRSC0VFfgVs6n4259vwWtDewCm1i_p\"></script>\n"
      + "<script src=\"/modules/contrib/ckeditor_accordion/js/accordion.frontend.min.js?s9vzg0\"></script>\n"
      + "\n"
      + "  </body>\n"
      + "</html>\n"
      + "";

}
